[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = [{name = "Vikas Kashyap", email = "vikaskashyaprock@gmail.com"}]
requires-python = ">=3.11"
dependencies = [
    "openai>=1.61.1",
]
